version: "2.1"

setup: true
orbs:
  continuation: circleci/continuation@0.5.0



workflows:
  setup-continuous-deployment:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/continue_deployment.yml
