version: 2.1

executors:
  default:
    docker:
      - image: cimg/azure:2024.03

jobs:

  pulumi:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install & Config Pulumi
          command: |
            curl -L https://get.pulumi.com/ | bash -s
            echo 'export PATH=${HOME}/.pulumi/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install KubeLogin
          command: |
            sudo az aks install-cli
      - run:
          name: Build
          working_directory: src/infrastructure
          command: |
            npm install
            npm run build
      - run:
          name: Pulumi
          working_directory: src/infrastructure
          command: |            
            pulumi login
            pulumi preview --stack << parameters.stack >>

workflows:
  preview:
    jobs:
      - pulumi
